### ISSUE TITLE
cargo ignores rust-toolchain.toml on macOS

### ISSUE THREAD

**Issue by hrls** [rust-lang/rustup#3069]
### Problem

`cargo` ignores toolchain specified in `rust-toolchain.toml` on macOS 10.15.7.
At the same time `rust-toolchain` works as expected and overrides default toolchain.

### Steps

1. `cargo init foobar && cd foobar`
2. `printf '[toolchain]\nchannel = "nightly"\n' > rust-toolchain.toml`
3. `rustc --version`

Expected `nightly` version (as on linux), but I've got system-wide default `stable` channel.

### Version

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.64.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/2.8.3)
os: Mac OS 10.15.7 [64-bit]
```

**Comment by ehuss** [comment]
Can you post the output of `rustup show`?  It should be working, and it may be possible there are other overrides in place. I would check for a directory override (`rustup override list`) or check if the `RUSTUP_TOOLCHAIN` environment variable is set.

**Comment by hrls** [comment]
```
Default host: x86_64-apple-darwin
rustup home:  /Users/hrls/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin
bpf
sbf

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)

```

**Comment by weihanglo** [comment]
I think ehuss was talking about rustup toolchain overriding rules. Could you check if any of the followings overrides your toolchain setup?

> 1. A [toolchain override shorthand](https://rust-lang.github.io/rustup/overrides.html#toolchain-override-shorthand) used on the command-line, such as cargo +beta.
> 1. The `RUSTUP_TOOLCHAIN` environment variable.
> 1. A [directory override](https://rust-lang.github.io/rustup/overrides.html#directory-overrides), set with the rustup override command.
> 1. The [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file.
> 1. The [default toolchain](https://rust-lang.github.io/rustup/overrides.html#default-toolchain).

Ref: https://rust-lang.github.io/rustup/overrides.html#overrides

I would also look into `which rustc` or `which cargo` to check if we really invoke cargo/rustc under rustup controls.

**Comment by hrls** [comment]
Only overriding by `rust-toolchain.toml` is presented. And it doesn't works.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/3259009/189736666-0f1fa91c-9a80-4f4f-8525-fe0b1fb30230.png">

**Comment by weihanglo** [comment]
It's really strange that the output of `rustup toolchain list` shows `nightly (override)`, but `rustup show` and `rustc --version` still not on nightly. What's the version of rustup you've got?

Really sorry I have no enough knowledge to help you debug rustup. Cargo here is wrapped by a [rustup proxy](https://rust-lang.github.io/rustup/concepts/proxies.html#proxies), which  controls the real overridden logic. If you are still stuck in this, I'd recommend to post an issue in [rust-lang/rustup](https://github.com/rust-lang/rustup).

(Sorry I don't have the permission to transfer issue to there)

**Comment by ehuss** [comment]
I asked on Zulip to get this transferred.  I'm also at a loss as to what could cause this.  

Another thing to try is to run `rustup which rustc` just to double-check which binary it is pointing at.

**Comment by 0xPoe** [comment]
I can't reproducer it on my macOS. What's your rustup version? 

My macOS info:
<details>
```shell
                    'c.          rustin@Rustins-MacBook-Pro.local
                 ,xNMM.          --------------------------------
               .OMMMMo           OS: macOS Big Sur 10.16 21G72 x86_64
               OMMM0,            Host: MacBookPro16,1
     .;loddo:' loolloddol;.      Kernel: 21.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 4 days, 19 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 238 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Monaco 12
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i9-9980HK (16) @ 2.40GHz
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M
       .cooc,.    .,coo:.        Memory: 18729MiB / 32768MiB
```
</details>

My rustup version:
```shell
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.64.0-nightly (f6f9d5e73 2022-08-04)`
```

By the way, are `bpf` and `sbf` your custom toolchains? How did you link it?  Could you try to remove them and see what happened?

**Comment by hrls** [comment]
`rustup 1.25.1 (2022-07-12)` installed from brew.
Removing custom toolchains doesn't solves problem.
Last two lines as proof that `rust-toolchain` works as expected.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/3259009/191475570-0debc6e0-4a70-4e97-ae77-e3e9fad918b8.png">

**Comment by FumiyaShibusawa** [comment]
Looking at your prompt above, It seems to at least work properly for rustup because both `rustup --version` and `rustup show` show its nightly version. They actually use the same method `rustup::config::Cfg::find_or_install_override_toolchain_or_default(&self, path: &Path)` to find any overrides.

Maybe `rustc` itself can't recognize its version somehow, or for backward compatibility, it only recognizes `rust-toolchain` file. It's weird anyway, though.
Found similar issue on SO: https://stackoverflow.com/a/66603312

And also I couldn't reproduce it either.
<img width="740" alt="スクリーンショット 2022-09-22 19 06 25" src="https://user-images.githubusercontent.com/17764944/191719996-9bca009c-10cb-4628-a501-9908020865d5.png">

**Comment by 0xPoe** [comment]
@hrls Could you please try [this solution](https://stackoverflow.com/questions/65348882/why-is-my-rustup-rust-toolchain-file-not-overriding-the-default/66603312#66603312)? (remove .toml)

**Comment by hrls** [comment]
`rustup show` works, but `cargo` or `rustc` fails with `error: caused by: invalid toolchain name: [toolchain]`

<img width="907" alt="image" src="https://user-images.githubusercontent.com/3259009/192507245-aa9b8ad8-ea6c-47ba-a98b-0c9dc637b428.png">

**Comment by rbtcollins** [comment]
I suspect you have old proxies.

Try this

`RUSTUP_FORCE_ARG0=rustup cargo version` and see what is output.

**Comment by rbtcollins** [comment]
Oh, just spotted this  - also note that `rust-toolchain` is not a TOML file. `rust-toolchain.toml` is a TOML file.

**Comment by hrls** [comment]
Yes, proxies were 1.21 when rustup is 1.25. Re-launching `rustup-init` solves problem. Thanks.
